### ISSUE TITLE
not available via vundle?

### ISSUE THREAD

**Issue by TheRojam** [idbrii/vim-gogo#2]
i added idbrii/vim-remarkjs and idbrii/vim-gogo to .vimrc in the [vundle](https://github.com/VundleVim/Vundle.vim) part but it seems my vim does not recognize this plugins

**Comment by idbrii** [comment]
@TheRojam I don't use vundle, but as far as I understand, you just put github plugins after  `vundle#begin()`:

```
Plugin 'idbrii/vim-remarkjs'
Plugin 'idbrii/vim-gogo'
```

Do you need to ask vundle to update plugins? You may need to open an issue on Vundle.

How do you know they don't work? Vundle error? Error executing `:Gogo`?

**Comment by TheRojam** [comment]
reading this nearly two years later i think you're totaly right. ;)
